
import { GoogleGenAI } from "@google/genai";

// IMPORTANT: Do NOT expose your API key in client-side code.
// This usage of process.env.API_KEY assumes it's being replaced by a build tool
// (like Vite or Webpack) with a value from a .env file.
// In a real production app, this call should be made from a secure backend server.
const apiKey = process.env.API_KEY;
if (!apiKey) {
    throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey });

export async function generateImageFromPrompt(prompt: string): Promise<string> {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '1:1',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Could not connect to the image generation service.");
  }
}
