
import React from 'react';
import Spinner from './Spinner';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error }) => {
  const renderContent = () => {
    if (isLoading) {
      return (
          <div className="text-center">
            <Spinner />
            <p className="mt-4 text-gray-400">Generating your masterpiece... this may take a moment.</p>
          </div>
      );
    }
    if (error) {
      return (
        <div className="text-center text-red-400 bg-red-900/50 p-4 rounded-lg">
          <p className="font-bold">An Error Occurred</p>
          <p>{error}</p>
        </div>
      );
    }
    if (imageUrl) {
      return (
        <img
          src={imageUrl}
          alt="Generated by AI"
          className="rounded-lg shadow-2xl w-full h-full object-contain transition-opacity duration-500 opacity-0 animate-fade-in"
          style={{ animationFillMode: 'forwards' }}
        />
      );
    }
    return (
      <div className="text-center text-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        <p className="mt-2">Your generated image will appear here.</p>
      </div>
    );
  };

  return (
    <div className="w-full aspect-square bg-gray-800/50 border-2 border-dashed border-gray-700 rounded-2xl flex items-center justify-center p-4 transition-colors duration-300">
      {renderContent()}
       <style>
        {`
          @keyframes fade-in {
            from { opacity: 0; transform: scale(0.95); }
            to { opacity: 1; transform: scale(1); }
          }
          .animate-fade-in {
            animation: fade-in 0.5s ease-out;
          }
        `}
      </style>
    </div>
  );
};

export default ImageDisplay;
